### PR TITLE
Fix MqttReceived same fix similar to RabbitMq

### PR DESCRIPTION
**Pull request by mircotamburini**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=2792) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=2792) before we can accept your contribution.<br/><br/>:x: mircotamburini [sign now](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=2792)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/elsa-workflows/elsa-core?pullRequest=2792) it.</sub>

**Review by sfmskywalker — APPROVED** [review]

**Comment by sfmskywalker** [comment]
Thanks @mircotamburini !

**Comment by mircotamburini** [comment]
You are welcome.
I'm developing 2 new Activity specific for Industrial protocol like OpcUa and Modbus so Elsa can be used like Iot Gateway.
Can be interesting?

**Comment by sfmskywalker** [comment]
Very interesting, but maybe not common enough for these to be adopted as part of the core repository? I realize there already are some activities in there that aren't used too often, and I am planning on leaving them out for Elsa 3 in order to keep the project manageable.

So instead, I am considering to setup a modules gallery of some sort (where modules are packages on NuGet) as an easy way for people to find 3rd party Elsa modules. Module authors such as yourself would then maintain their own packages and push them to NuGet.

To make that a little bit more friction-free, I'm thinking that perhaps the Elsa Modules Gallery could allow module authors to simply register their GitHub repo containing their Elsa module with activities, and **automatically** build & deploy them to NuGet. This way, authors don't have to setup CI/CD etc.

**Comment by sfmskywalker** [comment]
I'm sure you're right! :) But I have to find a balance between what I and other community members use regularly-ish and close to never in order to be able to maintain such a potential contribution. Presuming there aren't too many folks here using this (I may be wrong), then it would be best if someone who uses this regularly-ish to maintain the library. And of course, if it turns out more than one person is using this regularly, we can always consider moving it in at a later stage!

**Comment by mircotamburini** [comment]
I can ask if there is something to store a value in global cache visible to all Workflow instances?

something like global in node-red: https://nodered.org/docs/user-guide/context

**Comment by sfmskywalker** [comment]
It looks like that the documentation you linked to discusses context that is global across nodes (activities in Elsa) only. In Elsa, you would use Workflow Variables for similar functionality.

Nonetheless, you can store something in a global cache that is visible to all workflow instances, but we don't have anything for that out of the box.

But, that's easy enough to add using a couple of custom activities and JavaScript extensions that access a cache of your choice.

I imagine you would want 2 custom activities named e.g. `SetGlobalValue` and `GetGlobalValue`.
Similarly, you would extend the JavaScript engine with 2 functions named e.g. `setGlobalValue` and `getGlobalValue`.

These activities and JS functions would simply invoke e.g. `IDistributedCache` or `MemoryCache` (or something else entirely) to save & load a value by key.

To learn more about creating custom activities, please checkout this page: https://elsa-workflows.github.io/elsa-core/docs/next/extensibility/extensibility-custom-activities

And to learn more about creating custom JavaScript functions, please see this one: https://elsa-workflows.github.io/elsa-core/docs/next/extensibility/extensibility-javascript

**Comment by mircotamburini** [comment]
Ok , i understand... my idea is only in line with mqtt-activities also an stardard de-facto with opcua for Industry 4.0... but no problem.

**Pull request merged**
