### PR TITLE
Refactored docker build scripts

### PR DESCRIPTION
**Pull request by jwillmer**
1. I removed name references to `sample` and `monolith` since the user wants to host the dashboard. Telling him that it is a monolith or that we only see it as a sample/reference implementation is not interesting for him.
2. Refactored `Dockerfile` to allow us to build the dashboard for all platform architectures
3. Created a Readme that explains the manual process of building and using the image

### What I like to do next
- Setup multi arch build automation and deployment for the supplied changes. But we need to agree and merge the changes before I can do this
- Update Readme and dockerfile with a reference to the automatically build image

**Feature reference:** https://github.com/elsa-workflows/elsa-core/issues/733

### CODE REVIEW

**Review by sfmskywalker — APPROVED** [review]

**Comment by sfmskywalker** [comment]
Great stuff. What I'd like to see also is a docker file for **just** an Elsa server (without dashboard), and in the near future, a docker file for en Orleans Silo that hosts Elsa grains. Ideally we can do this in a layered approach, but we'll see what's possible.

**Comment by craigfowler** [comment]
Oh dear.  It seems that this PR has broken the build on AppVeyor 😱 

[Here's the failing build for the PR](https://ci.appveyor.com/project/sfmskywalker/elsa/builds/38493088) and then [here's the first build after it was merged, failing with the same error](https://ci.appveyor.com/project/sfmskywalker/elsa/builds/38493240).

I'm not particularly familiar with Docker (I've never used it in professional capacity), so even if this is a quick/easy fix, it would be helpful if someone else could take a look at the build failure.  @jwillmer or @sfmskywalker ?  Thanks!

**Comment by craigfowler** [comment]
@jwillmer Those npm issues have been ongoing for a long time.  I have it in the back of my mind to address them but they aren't actually breaking the build, they're more like warnings than outright errors (despite all of the red).  You need to read past those to see the actual error which breaks the build (at the very end of the build log).  That's brand new.

```
docker build -t elsaworkflows/elsadashboard-samples-monolith -f ./docker/ElsaDashboard.Samples.Monolith.Dockerfile .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: CreateFile C:\projects\elsa\docker\ElsaDashboard.Samples.Monolith.Dockerfile: The system cannot find the file specified.
Command exited with code 1
```

**Comment by jwillmer** [comment]
ah, o.k., sorry. Yes, I changed the naming of the files. So this is an easy renaming fix. I will provide a fix!

**Comment by jwillmer** [comment]
Now I'm confused. Apparently the docker build for appveyor is not used since 4 days?
image

**Pull request merged**
