### PR TITLE
Fix race condition for TriggerIndexingFinished/TriggersDeleted

### PR DESCRIPTION
**Pull request by jdevillard**
This PR fixes the race condition #2812  by adding a semaphore on RemoveWorkersAsync(Triggers)

### CODE REVIEW

**Comment by jdevillard** [comment]
This PR can be used as is. 

About the second point of #2812,, the use of the latest Azure Service Bus and the use of the processor doesn't throw the exception ( Handler already register), but for me there is a potential starvation because the processor is never disposed. I'll look deeper into this.

**Comment by jdevillard** [comment]
ok for what I've seen, bookmark are deleted in the store in the BookmarkIndexer : 

https://github.com/elsa-workflows/elsa-core/blob/2733a642f258187fb0717182d3ebd2e0d608eea8/src/core/Elsa.Core/Services/Bookmarks/BookmarkIndexer.cs#L95-L99

BUT the event BookmarkDeleted is never fired with the deleted bookmark : 

https://github.com/elsa-workflows/elsa-core/blob/2733a642f258187fb0717182d3ebd2e0d608eea8/src/activities/Elsa.Activities.AzureServiceBus/Consumers/UpdateWorkers.cs#L15

Q/ Should the method call not be 
```
await _workerManager.RemoveWorkersAsync(message.Bookmarks); 
```
and not
```
 await _workerManager.CreateWorkersAsync(message.Bookmarks); 
```

**Review by sfmskywalker — APPROVED** [review]

**Comment by sfmskywalker** [comment]
> About the second point of #2812,, the use of the latest Azure Service Bus and the use of the processor doesn't throw the exception ( Handler already register), but for me there is a potential starvation because the processor is never disposed. I'll look deeper into this.

You're right - we need to remove the workflow from the list in the `WorkerManager` when the processor raises an error. One easy way may be to either expose an event from the worker that the worker manager listens for. Alternatively, the worker constructor could accept a callback from the manager, allowing the manager to provide cleanup logic. Conceptually it's the same.

**Comment by sfmskywalker** [comment]
> ok for what I've seen, bookmark are deleted in the store in the BookmarkIndexer :
> 
> https://github.com/elsa-workflows/elsa-core/blob/2733a642f258187fb0717182d3ebd2e0d608eea8/src/core/Elsa.Core/Services/Bookmarks/BookmarkIndexer.cs#L95-L99
> 
> BUT the event BookmarkDeleted is never fired with the deleted bookmark :

That is a big problem. Will fix.

> 
> https://github.com/elsa-workflows/elsa-core/blob/2733a642f258187fb0717182d3ebd2e0d608eea8/src/activities/Elsa.Activities.AzureServiceBus/Consumers/UpdateWorkers.cs#L15
> 
> Q/ Should the method call not be
> 
> ```
> await _workerManager.RemoveWorkersAsync(message.Bookmarks); 
> ```
> 
> and not
> 
> ```
>  await _workerManager.CreateWorkersAsync(message.Bookmarks); 
> ```

Yes, that's another issue. Great find, this might explain some of the strange things I've seen in a production environment.

> final point : I think BookmarkDeleted event is missing after deleting oldBookmark in store.

Yep. I'll fix this too. 

Thank you for these findings!

**Comment by sfmskywalker** [comment]
I pushed a few updates that fixes the issues you mentioned. I'm about to test these shortly. Please let me know if you see any other issues.

**Pull request merged**
