### PR TITLE
Fix variable serialization

### PR DESCRIPTION
**Pull request by sfmskywalker**
This PR fixes variable serialization through the introduction of a non-polymorphic variable storage driver and by separting input serialization when sending messages through MassTransit. This ensures that dynamic objects are serialized "as-is" without also serializing their .NET type name, which would break the expected JSON format when serializing an expando object.

- - -
This change is [Reviewable](https://reviewable.io/reviews/elsa-workflows/elsa-core/5974)

### CODE REVIEW

**Review by raymonddenhaan — APPROVED** [review]

**Comment by rosca-sabina** [comment]
Hi @sfmskywalker @raymonddenhaan!

This commit seems to have introduced a bug when using MongoDB storage. When using MongoDB and `WorkflowInstanceStorageDriver` to store workflow variables, I'm getting the exception below. Looks like there's some sort of circular reference when serializing `JsonNode`.

```log
MongoDB.Bson.BsonSerializationException:
An error occurred while serializing the WorkflowState property of class Elsa.Workflows.Management.Entities.WorkflowInstance:
An error occurred while serializing the ActivityExecutionContexts property of class Elsa.Workflows.State.WorkflowState:
An error occurred while serializing the Properties property of class Elsa.Workflows.State.ActivityExecutionContextState:
An error occurred while serializing the Parent property of class System.Text.Json.Nodes.JsonNode:
...
An error occurred while serializing the Parent property of class System.Text.Json.Nodes.JsonNode:
Maximum serialization depth exceeded (does the object being serialized have a circular reference?).
   at MongoDB.Bson.IO.BsonWriter.EnterSerializationScope()
   at MongoDB.Bson.IO.BsonWriter.WriteStartDocument()
   at MongoDB.Bson.IO.BsonBinaryWriter.WriteStartDocument()
   at MongoDB.Bson.IO.WrappingBsonWriter.WriteStartDocument()
   at MongoDB.Bson.IO.ElementAppendingBsonWriter.WriteStartDocument()
   at MongoDB.Bson.Serialization.Serializers.DictionarySerializerBase`3.SerializeDocumentRepresentation(BsonSerializationContext context, TDictionary value)
   at MongoDB.Bson.Serialization.Serializers.DictionarySerializerBase`3.SerializeValue(BsonSerializationContext context, BsonSerializationArgs args, TDictionary value)
   at MongoDB.Bson.Serialization.Serializers.ClassSerializerBase`1.Serialize(BsonSerializationContext context, BsonSerializationArgs args, TValue value)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Serialize(BsonSerializationContext context, BsonSerializationArgs args, TClass value)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Serialize(IBsonSerializer serializer, BsonSerializationContext context, Object value)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.SerializeNormalMember(BsonSerializationContext context, Object obj, BsonMemberMap memberMap)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.SerializeMember(BsonSerializationContext context, Object obj, BsonMemberMap memberMap)
...
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.SerializeMember(BsonSerializationContext context, Object obj, BsonMemberMap memberMap)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.SerializeClass(BsonSerializationContext context, BsonSerializationArgs args, TClass document)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Serialize(BsonSerializationContext context, BsonSerializationArgs args, TClass value)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Serialize(IBsonSerializer serializer, BsonSerializationContext context, Object value)
   at MongoDB.Bson.Serialization.Serializers.BsonDocumentWrapperSerializer.SerializeValue(BsonSerializationContext context, BsonSerializationArgs args, BsonDocumentWrapper value)
   at MongoDB.Bson.Serialization.Serializers.BsonValueSerializerBase`1.Serialize(BsonSerializationContext context, BsonSerializationArgs args, TBsonValue value)
   at MongoDB.Bson.Serialization.Serializers.BsonValueSerializerBase`1.Serialize(BsonSerializationContext context, BsonSerializationArgs args, TBsonValue value)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Serialize[TValue](IBsonSerializer`1 serializer, BsonSerializationContext context, TValue value)
   at MongoDB.Bson.Serialization.Serializers.BsonDocumentSerializer.SerializeValue(BsonSerializationContext context, BsonSerializationArgs args, BsonDocument value)
   at MongoDB.Bson.Serialization.Serializers.BsonValueSerializerBase`1.Serialize(BsonSerializationContext context, BsonSerializationArgs args, TBsonValue value)
   at MongoDB.Bson.Serialization.Serializers.ElementAppendingSerializer`1.Serialize(BsonSerializationContext context, BsonSerializationArgs args, TDocument value)
   at MongoDB.Bson.Serialization.Serializers.ElementAppendingSerializer`1.MongoDB.Bson.Serialization.IBsonSerializer.Serialize(BsonSerializationContext context, BsonSerializationArgs args, Object value)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Serialize(IBsonSerializer serializer, BsonSerializationContext context, Object value)
   at MongoDB.Driver.Core.WireProtocol.Messages.Encoders.BinaryEncoders.CommandMessageBinaryEncoder.WriteType0Section(BsonBinaryWriter writer, Type0CommandMessageSection section)
   at MongoDB.Driver.Core.WireProtocol.Messages.Encoders.BinaryEncoders.CommandMessageBinaryEncoder.WriteSection(BsonBinaryWriter writer, CommandMessageSection section, Int64 messageStartPosition)
   at MongoDB.Driver.Core.WireProtocol.Messages.Encoders.BinaryEncoders.CommandMessageBinaryEncoder.WriteSections(BsonBinaryWriter writer, IEnumerable`1 sections, Int64 messageStartPosition)
   at MongoDB.Driver.Core.WireProtocol.Messages.Encoders.BinaryEncoders.CommandMessageBinaryEncoder.WriteMessage(CommandMessage message)
   at MongoDB.Driver.Core.WireProtocol.Messages.Encoders.BinaryEncoders.CommandRequestMessageBinaryEncoder.WriteMessage(CommandRequestMessage message)
   at MongoDB.Driver.Core.WireProtocol.Messages.Encoders.BinaryEncoders.CommandRequestMessageBinaryEncoder.MongoDB.Driver.Core.WireProtocol.Messages.Encoders.IMessageEncoder.WriteMessage(MongoDBMessage message)
   at MongoDB.Driver.Core.Connections.BinaryConnection.SendMessagesHelper.EncodeMessages(CancellationToken cancellationToken, List`1& sentMessages)
   at MongoDB.Driver.Core.Connections.BinaryConnection.SendMessagesAsync(IEnumerable`1 messages, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.PooledConnection.SendMessagesAsync(IEnumerable`1 messages, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.SendMessageAndProcessResponseAsync(CommandRequestMessage message, Int32 responseTo, IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ExecuteAsync(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocolAsync[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocolAsync(IChannelSource channelSource, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.WriteCommandOperation`1.ExecuteAsync(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.FindAndModifyOperationBase`1.ExecuteAttemptAsync(RetryableWriteContext context, Int32 attempt, Nullable`1 transactionNumber, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteOperationExecutor.ExecuteAsync[TResult](IRetryableWriteOperation`1 operation, RetryableWriteContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteOperationExecutor.ExecuteAsync[TResult](IRetryableWriteOperation`1 operation, IWriteBinding binding, Boolean retryRequested, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperationAsync[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperationAsync[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at Elsa.MongoDb.Common.MongoDbStore`1.SaveAsync(TDocument document, CancellationToken cancellationToken)
   at Elsa.MongoDb.Modules.Management.MongoWorkflowInstanceStore.SaveAsync(WorkflowInstance instance, CancellationToken cancellationToken)
   at Elsa.Workflows.Management.Services.WorkflowInstanceManager.SaveAsync(WorkflowInstance workflowInstance, CancellationToken cancellationToken)
   at Elsa.Workflows.Management.Services.WorkflowInstanceManager.SaveAsync(WorkflowState workflowState, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.DefaultWorkflowRuntime.SaveWorkflowStateAsync(WorkflowState workflowState, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.DefaultWorkflowRuntime.StartWorkflowAsync(IWorkflowHost workflowHost, StartWorkflowRuntimeParams options)
   at Elsa.Workflows.Runtime.Services.DefaultWorkflowRuntime.StartWorkflowAsync(IWorkflowHost workflowHost, StartWorkflowRuntimeParams options)
   at Elsa.Workflows.Runtime.Services.DefaultWorkflowRuntime.StartWorkflowAsync(String definitionId, StartWorkflowRuntimeParams options)
```

**Comment by rosca-sabina** [comment]
Also, apart from the serialization exception, there's the issue of knowing the workflow variables' type when reading the workflow instance back from MongoDB. If the new `Variables` dictionary doesn't contain type information anymore like `PersistentVariablesDictionary` did, how will we be able to cast the workflow variables from `JsonNode` to the original type when reading the workflow from MongoDB.

**Comment by stephanmelzer** [comment]
I have the same problem and went back to version 3.2.0. @sfmskywalker Can you please look into the problem?

**Comment by sfmskywalker** [comment]
Thanks for reporting! I'll have a look soon.

**Comment by sfmskywalker** [comment]
So, the issue is. indeed, that the serializer doesn't know how to deserialize back into `JsonNode` types. To fix this, I have pushed a custom `BsonSerializer` for `JsonNode` values. This will successfully deserialize JSON into `JsonNode` objects (assuming I covered all type cases—there may be some I've missed, but we can patch those as we discover them).

Once we have a `VariablesDictionary` of concrete `JsonNode` values, the system will deserialize them into strongly-typed .NET types using the .NET type of the workflow variable.

For instance, if we have a variable of type `string`, the serialized variables dictionary will contain a `JsonValue` of type `string`, which will be parsed into a `string`, given the variable's type.

If the variable is of type `Foo`, it will have been serialized and deserialized as a `JsonObject`, which in turn will be deserialized into `Foo`.

**Comment by sfmskywalker** [comment]
https://github.com/elsa-workflows/elsa-core/pull/6043

**Pull request merged**
