### PR TITLE
make type name helper aware of generics

### LINKED ISSUE #4440: Elsa V3: Cannot use ForEach activity in coded workflows more than once per application
Hi, I have an app with two separate workflows (materialized by dependency injection, `elsa.AddWorkflowsFrom<Program>()`), one of which used the *ForEach* activity. Everything worked fine.

Then I added a new workflow to the application, which also contains a *ForEach* activity (using a different item type), and now on startup it throws the following exception:

```
System.Reflection.TargetException
  HResult=0x80131603
  Nachricht = Object does not match target type.
  Quelle = System.Private.CoreLib
  Stapelüberwachung:
   bei System.Reflection.MethodBase.ValidateInvokeTarget(Object target)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei System.Reflection.PropertyInfo.GetValue(Object obj)
   bei Elsa.Extensions.ActivityDescriptorExtensions.<>c__DisplayClass3_0.<GetWrappedInputProperties>b__2(InputDescriptor x) in C:\Users\arose\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\3402388f89ea499c821c5cac84c004026ce00\78\26692dc8\ActivityDescriptorExtensions.cs: Zeile49
   bei System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   bei System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   bei Elsa.Extensions.ActivityDescriptorExtensions.GetWrappedInputProperties(ActivityDescriptor activityDescriptor, IActivity activity) in C:\Users\arose\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\3402388f89ea499c821c5cac84c004026ce00\78\26692dc8\ActivityDescriptorExtensions.cs: Zeile49
   bei Elsa.Workflows.Core.Services.IdentityGraphService.AssignInputOutputs(IActivity activity) in C:\Users\arose\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\3402388f89ea499c821c5cac84c004026ce00\62\e3db407a\IdentityGraphService.cs: Zeile75
   bei Elsa.Workflows.Core.Services.IdentityGraphService.AssignIdentities(ICollection`1 flattenedList) in C:\Users\arose\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\3402388f89ea499c821c5cac84c004026ce00\62\e3db407a\IdentityGraphService.cs: Zeile67
   bei Elsa.Workflows.Core.Builders.WorkflowBuilder.<BuildWorkflowAsync>d__67.MoveNext() in C:\Users\arose\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\3402388f89ea499c821c5cac84c004026ce00\f2\e0407a2b\WorkflowBuilder.cs: Zeile161
   bei Elsa.Workflows.Runtime.Providers.ClrWorkflowProvider.<BuildWorkflowAsync>d__7.MoveNext()
   bei Elsa.Workflows.Runtime.Providers.ClrWorkflowProvider.<>c__DisplayClass6_0.<<GetWorkflowsAsync>b__0>d.MoveNext()
   bei Elsa.Workflows.Runtime.Providers.ClrWorkflowProvider.<GetWorkflowsAsync>d__6.MoveNext()
   bei Open.Linq.AsyncExtensions.Extensions.<ToList>d__177`1.MoveNext()
   bei Elsa.Workflows.Runtime.Services.DefaultWorkflowDefinitionStorePopulator.<PopulateStoreAsync>d__8.MoveNext()
   bei Elsa.Workflows.Runtime.Services.DefaultRegistriesPopulator.<PopulateAsync>d__4.MoveNext()
   bei Elsa.Workflows.Runtime.HostedServices.PopulateRegistriesHostedService.<StartAsync>d__2.MoveNext()
   bei Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   bei Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   bei Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   bei Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   ...
```

The exception is thrown [here](https://github.com/elsa-workflows/elsa-core/blob/12f9e0844bfb864264e56d0dcdd101383257c2f1/src/modules/Elsa.Workflows.Core/Extensions/ActivityDescriptorExtensions.cs#L42) when trying to execute `x => (Input?)x.ValueGetter(activity)` when processing the first *ForEach* activity (the one from the workflow which was working before).

As soon as I remove the *ForEach* from the new workflow the app runs fine again.

### PR DESCRIPTION
**Pull request by rose-a**
Fixes #4440

### CODE REVIEW

**Comment by rose-a** [comment]
@dotnet-policy-service agree

**Comment by rose-a** [comment]
Fix is not complete yet... still goes wrong if the type name is specified in the `ActivityAttribute`

**Comment by rose-a** [comment]
Ready to merge from my side...

**Comment by sfmskywalker** [comment]
Awesome, and just in time for the RC2 release, too!

**Review by sfmskywalker — APPROVED** [review]

**Pull request merged**
