### PR TITLE
Allow sending input as http request body and output the response content

### PR DESCRIPTION
**Pull request by tanelkuhi**
Our client has this specific requirement to fetch a file from an url, and then make a request to another url with that file attached as content. These changes aim to solve this.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=3473) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=3473) before we can accept your contribution.<br/><br/>:x: tanelkuhi [sign now](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=3473)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/elsa-workflows/elsa-core?pullRequest=3473) it.</sub>

**Comment by johnwc** [comment]
This adds complexity that is unneeded. The activity already does exactly what you need it to do. You only need to use it properly and read/write the correct input/output properties with activities before and after the Send Http Activity.

**Comment by tanelkuhi** [comment]
@johnwc Could you elaborate further about reading/writing the inputs and outputs, please? Are there some activities you can put before or after SendHttpRequest, that allow choosing one of the properties as output?

**Comment by constantine-v** [comment]
@tanelkuhi You can switch Content field type to Javascript and either specify input (`return input;`) or any specific activity output (`return activities.my_activity_name.Output();`) as source.

**Pull request closed without merging**
