### PR TITLE
Change MongoDB classmap registration for SerializedKeyValuePair

### PR DESCRIPTION
**Pull request by rosca-sabina**
This PR changes the way the MongoDB class map registration is done for class `SerializedKeyValuePair`.

In scenarios where the Elsa Workflows registration must be called multiple times (like for test setup methods), `BsonClassMap.RegisterClassMap` throws an exception the second time it's called. I replaced it with `BsonClassMap.TryRegisterClassMap`, which doesn't throw an exception when a class map was already registered.

- - -
This change is [Reviewable](https://reviewable.io/reviews/elsa-workflows/elsa-core/5870)

### CODE REVIEW

**Comment by rosca-sabina** [comment]
Hello @sfmskywalker! Is there any chance we could get this change as part of the next 3.2 release candidate?

**Review by sfmskywalker — APPROVED** [review]

**Comment by sfmskywalker** [comment]
Definitely. Thanks for the fix!

**Comment by sfmskywalker** [comment]
I tried to change the destination branch from main to patch/3.2.x, but this causes a big diff. Would you mind creating a new PR? Sorry about that.

**Comment by rosca-sabina** [comment]
Hi! I created a new PR into patch/3.2.x: https://github.com/elsa-workflows/elsa-core/pull/5877

**Comment by sfmskywalker** [comment]
Perfect. Please close this PR (or I can do it if you prefer). Thanks again!

**Comment by rosca-sabina** [comment]
Thanks as well!

Out of curiosity, how will the fix make its way into the main branch? Will patch/3.2.x be merged into main once release 3.2.0 is out?

**Comment by sfmskywalker** [comment]
That's exactly right: `patch/3.2.x` will be merged into `main`, either after 3.2.0 is out, or even before then.

**Comment by rosca-sabina** [comment]
Got it, thanks for the explanation!

**Pull request closed without merging**
