### PR TITLE
Fix CleanupExpiredMessages Error (#4810)

### PR DESCRIPTION
**Pull request by faith0831**
This change is [Reviewable](https://reviewable.io/reviews/elsa-workflows/elsa-core/4980)

### CODE REVIEW

**Comment by sfmskywalker** [comment]
Hello @faith0831 , thank you for submitting a PR. Can you explain what the issue is and how this PR fixes that? I noticed that it removes the use of the pagination args, which might have other consequences.

**Comment by mohdali** [comment]
> Hello @faith0831 , thank you for submitting a PR. Can you explain what the issue is and how this PR fixes that? I noticed that it removes the use of the pagination args, which might have other consequences.

It is related to #4810 for MySQL as LIMIT is not supported in sub queries. However, I'm not sure if removing the pagination is the way to go as it seems to be possible to replace the subquery with a LEFT JOIN. I didn't get the chance to test that though.

@faith0831 is it possible to use a LEFT JOIN instead of getting rid of pagination completely?

**Comment by sfmskywalker** [comment]
@mohdali I see, thanks for the clarification. We shouldn't drop paging support because it might negatively impact other users that use other database servers and where doing a batched deletion of workflow inbox messages is preferred (in case of high numbers of records).

Additionally, if the paging SQL clauses cause an issue for MySQL for the WorkflowInbox table, it will also be an issue for all other DB tables, which means that this PR might "fix" one affected area, it will not fix the root issue.

**Comment by faith0831** [comment]
> > Hello @faith0831 , thank you for submitting a PR. Can you explain what the issue is and how this PR fixes that? I noticed that it removes the use of the pagination args, which might have other consequences.您好，感谢您提交 PR。你能解释一下问题是什么以及这个 PR 是如何解决这个问题的吗？我注意到它删除了分页参数的使用，这可能会产生其他后果。
> 
> @sfmskywalker It is related to #4810 for MySQL as LIMIT is not supported in sub queries. However, I'm not sure if removing the pagination is the way to go as it seems to be possible to replace the subquery with a LEFT JOIN. I didn't get the chance to test that though.它与 MySQL 的 #4810 相关，因为子查询不支持 LIMIT。但是，我不确定删除分页是否是要走的路，因为似乎可以用 LEFT JOIN 替换子查询。不过，我没有机会测试它。
> 
> @faith0831 is it possible to use a LEFT JOIN instead of getting rid of pagination completely?是否可以使用 LEFT JOIN 而不是完全摆脱分页？

@mohdali  Thank you for your assistance, I will continue to try to solve this problem.

**Comment by faith0831** [comment]
> @mohdali I see, thanks for the clarification. We shouldn't drop paging support because it might negatively impact other users that use other database servers and where doing a batched deletion of workflow inbox messages is preferred (in case of high numbers of records).
> 
> Additionally, if the paging SQL clauses cause an issue for MySQL for the WorkflowInbox table, it will also be an issue for all other DB tables, which means that this PR might "fix" one affected area, it will not fix the root issue.

Thank you for your reply @sfmskywalker, this PR indeed has the issues you mentioned.

**Comment by sfmskywalker** [comment]
@faith0831 @mohdali Should we keep this PR open, change it to Draft, or abandon?

**Comment by mohdali** [comment]
@sfmskywalker we need to change how the MySql query for clearing the inbox is executed. I didn't get the time to check the possible solution. I think this PR can be changed to draft.

**Comment by mohdali** [comment]
@sfmskywalker In order to resolve this issue we need to change the `DeleteManyAsync` query specifically for MySQL to avoid using pagination. I think it is still possible to batch the deletion in MySQL but needs to be done using a subquery instead.

In that case, what is the recommended approach? Show we create a new `IWorkflowInboMessageStore` in `Elsa.EntitiyFrameworkCore.MySql` and let it hide the default store? We only need to add that store if the Workflow Inbox feature is enabled though (not sure what is the correct pattern here).

I think in general there will be some exceptions like this depending on each DB capabilities, we need to have a clear pattern to handle those cases.

**Comment by raymonddenhaan** [comment]
Closing this PR since the `IWorkflowInboxMessageStore` is no longer used in the 3.3 preview

**Pull request closed without merging**
