### PR TITLE
feature: Add created date time to filter

### PR DESCRIPTION
**Pull request by bbenameur**
Issue: https://github.com/elsa-workflows/elsa-core/issues/4937
Need:

Current: 
At the endpoint **elsa/api/workflow-instances** currently return all workflow instances even we have millions of instances !!

Target:
Add two properties to filters, FromCreatedAt and ToCreatedAt to help us to get instances between 2 date times.

### CODE REVIEW

**Comment by bbenameur** [comment]
@sfmskywalker

**Comment by bbenameur** [comment]
Hello @sfmskywalker, do you have any questions about this PR?
Sorry, I can't add reviewers maby i dont have permissions.

**Comment by sfmskywalker** [comment]
Hi @bbenameur , not yet - I just haven't found the time to go over it :)

**Review by sfmskywalker — APPROVED** [review]
Very good, thanks!

**Comment by sfmskywalker** [comment]
Hi @bbenameur , just a quick heads up: we are about to merge [this PR](https://github.com/elsa-workflows/elsa-core/pull/4957) that changes the API a bit. In summary, it offers more options to filter by date ranges, including CreatedAt (which you added via your PR), UpdatedAt and FinishedAt, on top of a few more filters.

This will change the API in the following way (example):

```
https://localhost:5001/elsa/api/workflow-instances?TimestampFilters=[{"Column": "CreatedAt", "Operator": 1, "Timestamp": "2024-02-16T00:00:00"}]
```

Notice that for the date ranges, we now have to provide a TimestampFilters parameter when using GET requests.
The API was updated to also support POST requests, which makes it simpler to post these filters.

Please let me know if you have any questions or concerns about this upcoming change.

Thanks again for your contributions!

**Comment by bbenameur** [comment]
Hello, @sfmskywalker ia agree is the best and flexible way, thanks.

**Pull request merged**
