### PR TITLE
Change extension method name to UseAzureBlobLockProvider

### LINKED ISSUE #1142: Extension method to add Azure distributed locking has incorrect name
The method to add Azure distributed locking to Elsa has name [UseSqlServerLockProvider](https://github.com/elsa-workflows/elsa-core/blob/master/src/locking/Elsa.DistributedLocking.AzureBlob/DistributedLockingOptionsExtensions.cs#L10).

That is the same name as used in the [Sql Server distributed locking](https://github.com/elsa-workflows/elsa-core/blob/master/src/locking/Elsa.DistributedLocking.SqlServer/DistributedLockingOptionsExtensions.cs#L7), so it could be a copypaste mistake.

### PR DESCRIPTION
**Pull request by mdrjob**
Fixes #1142.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=1143) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=1143) before we can accept your contribution.<br/><br/>:x: mdrjob [sign now](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=1143)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/elsa-workflows/elsa-core?pullRequest=1143) it.</sub>

**Review by sfmskywalker — APPROVED** [review]
Thanks for catching AND fixing that 👍🏻

**Comment by sfmskywalker** [comment]
I think the only thing left to do is for you to sign the CLA, then we can merge.

**Comment by mdrjob** [comment]
I signed the CLA just now.

**Comment by sfmskywalker** [comment]
Thanks!

**Pull request merged**
