### PR TITLE
Add multiple languages

### PR DESCRIPTION
**Pull request by landonzeng**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=2523) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=2523) before we can accept your contribution.<br/><br/>:x: landonzeng [sign now](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=2523)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/elsa-workflows/elsa-core?pullRequest=2523) it.</sub>

**Review by sfmskywalker — APPROVED** [review]
Thank you!

**Comment by landonzeng** [comment]
I have a question, how do I use zh-cn in my project?Is it changing <html dir="ltr" lang="en"> to <html dir="ltr" lang="zh-cn"> in index.html?

**Comment by sfmskywalker** [comment]
Sure. You can change the culture using the `culture` attribute. Example:

```html
<elsa-studio-root culture="zh-cn">
```

**Comment by landonzeng** [comment]
> Sure. You can change the culture using the `culture` attribute. Example:
> 
> ```
> <elsa-studio-root culture="zh-cn">
> ```

Is it in the index.html file? I changed it, but it didn't work
QQ截图20211125180547
ddddd

**Comment by sfmskywalker** [comment]
Yes, exactly like that.

However, there appear to be two issues:

1. Not all components get the culture injected. For example, the `elsa-studio-home.tsx` component, it needs some culture tunneling (I will show how to fix it for the that component, then you can do the same for other components when needed).
2. Apparently, the culture code should be defined as `zh-CN` (notice all-caps CN). This needs to be changed in all localization.ts files and of course in index.html. Sorry, I didn't know.

Regarding the tunneling, take a look at [this diff](https://github.com/elsa-workflows/elsa-core/commit/beaaf6eafba2a1b2cadf37d2bb6cddabb9dde6c6):

```typescript
Tunnel.injectProps(ElsaStudioHome, ['culture']);
```

This has to be done for all components that don't already do this (most of them should have this already, but not all).

**Comment by landonzeng** [comment]
Ok, I'll change it to zh-CN now

**Comment by toyzz2** [comment]
hello，in Elsa3 `<elsa-studio culture="zh-CN"></elsa-studio>` , But it doesn't work .
I mimic this example [https://github.com/elsa-workflows/elsa-core](url)
how do I use zh-cn in my project? thanks

**Comment by sfmskywalker** [comment]
Hi @toyzz2 , Elsa 3 doesn't currently support localization, but I created an issue for this just now here: https://github.com/elsa-workflows/elsa-studio/issues/23

**Pull request merged**
