### PR TITLE
Update FastEndpoints* nuget packages to 5.21.2 version

### LINKED ISSUE #4747: Please update FastEndpoints nuget package version
Currently, Elsa.Api.Common depends on below BETA nuget packages:
- [FastEndpoints](https://www.nuget.org/packages/FastEndpoints/) (>= 5.20.1.7-beta)
- [FastEndpoints.Security](https://www.nuget.org/packages/FastEndpoints.Security/) (>= 5.20.1.7-beta)
- [FastEndpoints.Swagger](https://www.nuget.org/packages/FastEndpoints.Swagger/) (>= 5.20.1.7-beta)

They all already have official released version already, please update the version number to 5.21.2.

### PR DESCRIPTION
**Pull request by NightWuYo**
Use the latest release version, instead of the beta version.

Fixes #4747

### CODE REVIEW

**Comment by NightWuYo** [comment]
@dotnet-policy-service agree

**Comment by sfmskywalker** [comment]
Hi @NightWuYo , there seems to be an issue with this PR - it contains 99 changes, even though only one file should have been affected. I tried switching the PR to target the v3.02 branch, but that didn't help. If you want, please create a new PR targeting the v3.0.2 branch (I dropped my own commit so we can take yours). Thank you for your help!

**Comment by NightWuYo** [comment]
@sfmskywalker 
It has been some time since this PR was created, that's why we got some conflicts.

I have synced my branch to latest main.
Your change is still in the main branch.

Currently the only change is to remove one extra space ...

Feel free to merge this PR or just discard it.

**Review by sfmskywalker — APPROVED** [review]

**Comment by sfmskywalker** [comment]
@NightWuYo I reverted my commit on the v3.0.2 branch (see https://github.com/elsa-workflows/elsa-core/commit/900aac6d56c413a450e85a4af78c19b27417ca9f) - if you don't mind, please create a PR against that branch, then it should be good. If it's too much hassle, just let me know and I will take care of it. Thank you.

**Comment by NightWuYo** [comment]
@sfmskywalker 
Thanks, I have created https://github.com/elsa-workflows/elsa-core/pull/4764.

**Comment by sfmskywalker** [comment]
Thank you 🙌🏻

**Pull request closed without merging**
