### PR TITLE
Workflow status enum should be converted to int and not string when persisting with EntityFramework

### PR DESCRIPTION
**Pull request by cando**
This is needed since the SQL [_WorkflowInstances]_ table expects:
`[Status] int NOT NULL`

### CODE REVIEW

**Comment by sfmskywalker** [comment]
Or perhaps we can fix the migrations such that it generates a string not null column instead of an int not null?

**Comment by cando** [comment]
@sfmskywalker You mean something like that? Forgive me if I've done something wrong with migrations, but it's the first time I've used them :)

**Comment by sfmskywalker** [comment]
Exactly like that 👍🏻

But since we haven’t released anything yet officially, feel free to first delete the Migrations folder first and then generate them again like you did. 

If your unsure then that’s fine too. Just let me know.

**Comment by cando** [comment]
It turned out that the InitialCreate migration was alredy correct.

The only correction needed is on the [sqlserver-create.sql](https://github.com/elsa-workflows/elsa-core/blob/develop/src/persistence/Elsa.Persistence.EntityFrameworkCore/sqlserver-create.sql) in the root folder.

**Comment by sfmskywalker** [comment]
Ah, good find! No worries, I appreciate you looked into it.

**Pull request merged**
