### PR TITLE
Drop NET 7 support and cleanup NuGet package references

### PR DESCRIPTION
**Pull request by lahma**
* NET 7 is no longer supported
* `Directory.Packages.props` should mandate used versions
* Add NuGet audit mode setting to show any problems during restore
* `System.Text.Json` should be `8.0.4 `which is patched against security vulnerabilities

- - -
This change is [Reviewable](https://reviewable.io/reviews/elsa-workflows/elsa-core/5828)

### CODE REVIEW

**Review by sfmskywalker — APPROVED** [review]
Many thanks @lahma 🔥

**Comment by lahma** [comment]
I had to make small tweaks still. Hopefully getting a green build soon 😅

**Comment by lahma** [comment]
OK now should report problems during restore and build is green. If I alter package references in projects (remove explicit) I start to get warnings about vulnerable packages.

**Comment by sfmskywalker** [comment]
The PR build step is all green - which is good enough - the SonarCloud Code Analysis step tends to take a long time to report back for some reason, but this is not of your doing. If you're happy with the PR then I am, too.

**Pull request merged**
