### PR TITLE
http endpoint handling a single workflow

### PR DESCRIPTION
**Pull request by vlad-crisan**
an http endpoint now must match exactly one workflow
matching multiple is considered ambiguous and returns 500

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=1211) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=1211) before we can accept your contribution.<br/><br/>:x: vlad-crisan [sign now](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=1211)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/elsa-workflows/elsa-core?pullRequest=1211) it.</sub>

**Comment by vlad-crisan** [comment]
image
example of outcome when there is ambiguity.

@sfmskywalker let me know what you think about this

**Comment by vlad-crisan** [comment]
fixes #1188

**Review by sfmskywalker — APPROVED** [review]
I think it looks great. Thanks!

**Pull request merged**
