### PR TITLE
Changed Variables.cs to full IDictionary with ConcurrentDictionary<string, object> backing-store

### PR DESCRIPTION
**Pull request by Andale-online**
Changed Variables.cs to full IDictionary with ConcurrentDictionary<string, object> backing-store
This should be a 1:1 drop in and work even in resumed flows.
Now i get objects (the originals) and you get JTokens *CoughSweat*

BTW i think it may perform better because convert to jtoken is only done when needed. (Dont kill me if not)

This should even be a lit more thread-safe - (there should be some locks somewhere i think to be 100% safe....)

Lotsa shoulds... :-D Could you give it a look please? This would straighten the GetVariable mess in my flows and reduces converts a lot...

### CODE REVIEW

**Comment by sfmskywalker** [comment]
Did you test it also with long running workflows where values are restored from persistence upon resuming workflows? Just want to make sure that the expectation of being able to store an object of a given type is also then returned in that type when rehydrates.

**Comment by Andale-online** [comment]
Err... Got a sample to test?

**Comment by sfmskywalker** [comment]
Sure, try this: https://github.com/elsa-workflows/elsa-samples/blob/master/src/Elsa.Samples.UserRegistration/user-registration-workflow.json

Perhaps easiest to clone the entire example and replace the Elsa package reference with full Elsa source code from your branch.

**Comment by Andale-online** [comment]
Got it running and did registration.

**Comment by sfmskywalker** [comment]
Allright, then we'll give it  go. Thanks!

**Pull request merged**
