### PR TITLE
.NET 7 Support

### PR DESCRIPTION
**Pull request by mohdali**
Support for .NET 7

**Note**: MySQL Provider is still in alpha release. Reference to the alpha version is added so that samples will build. However, not clear when it will be released.

### CODE REVIEW

**Comment by mihey8800** [comment]
I see *.ps scripts still using .net 6. Look plz =)

**Comment by mohdali** [comment]
> I see *.ps scripts still using .net 6. Look plz =)

Yes you are right. I forgot to update dovker images also. Thanks for highlighting :)

**Comment by Nico-VanHaaster** [comment]
Is there any ETA on this PR? ELSA .NET 7 is blocking us from upgrading our full stack to .NET7

**Comment by mihey8800** [comment]
hi. I added DocumentApprovalWorkflow from samples.
image

trying to open it in workflow registry.

Reciving: https://localhost:5001/api/v1/workflow-registry/DocumentApprovalWorkflow/Latest 

MissingMethodException - Method not found: 'System.Collections.Generic.IDictionary`2<System.String,System.Object> AutoMapper.IMappingOperationOptions.get_Items()'.".

Looks like some packages need to be updated.

**Comment by Nico-VanHaaster** [comment]
> hi. I added DocumentApprovalWorkflow from samples. image
> 
> trying to open it in workflow registry.
> 
> Reciving: https://localhost:5001/api/v1/workflow-registry/DocumentApprovalWorkflow/Latest
> 
> MissingMethodException - Method not found: 'System.Collections.Generic.IDictionary`2<System.String,System.Object> AutoMapper.IMappingOperationOptions.get_Items()'.".
> 
> Looks like some packages need to be updated.

This issue is due to a change in Automapper that has been addressed in a previous PR that upgrades Automapper to 12.0

https://github.com/elsa-workflows/elsa-core/pull/3483#event-7939147471

**Comment by mohdali** [comment]
> Is there any ETA on this PR? ELSA .NET 7 is blocking us from upgrading our full stack to .NET7

The PR is merged and preview packages are published to myGet.

Please check if any further issues.

**Pull request merged**
