### PR TITLE
Feature/expression deserialization 4786

### PR DESCRIPTION
**Pull request by tulrichtrimble**
Variables in Expressions are not being deserialized and so their values are empty in Activity execution. This adds "Variable" to the list of well-known aliased types and implements an Expression converter to handle this and future deserializations. 

See also [issue 4786](https://github.com/elsa-workflows/elsa-core/issues/4786).

### CODE REVIEW

**Comment by tulrichtrimble** [comment]
@dotnet-policy-service agree company="Trimble"

**Comment by sfmskywalker** [comment]
Hi @tulrichtrimble , thank you for the PR! Would you mind showing us a scenario where it would break without the PR, so that we can see what this PR fixes specifically?

**Comment by tulrichtrimble** [comment]
Hi @sfmskywalker. Apologies for the delay. Technical and day job issues had me occupied. 

The issue I found was that a serialized workflow doesn't rehydrate Variables in Expressions. When associated to an Activity `In` as outlined by the sample code in issue [4786](https://github.com/elsa-workflows/elsa-core/issues/4786), the result  the expression is a JSON Object, which is inoperative for the purposes of data addressability.

For example, creating a WriteLine activity as follows:
```csharp
var tempVariable = workflowBuilder.WithVariable<string>("variableName", "Some Value");
var writeLine = new WriteLine(tempVariable);
```
yields a runtime object whose expression value, `writeLine.Text.Expression.Value` is

```
{Elsa.Workflows.Memory.Variable<string>}
    Id: "Workflow1:variable-1"
    Name: "variableName"
    StorageDriverType: {Name = "WorkflowStorageDriver" FullName = "Elsa.Workflows.Services.WorkflowStorageDriver"}
    Value: "Some Value"
```

If we then serialize and deserialize its containing workflow and get a reference to the same object
```csharp
var flow = new Flowchart()
{
    Activities = new IActivity[] { writeLine },
    Start = writeLine
};

workflowBuilder.Root = flow;

var workflow = await workflowBuilder.BuildWorkflowAsync();

// Success: prints SomeValue. Writeline.Text MemoryBlockReference refers to tempVariable
await workflowRunner.RunAsync(workflow);

var serialized = workflowSerializer.Serialize(workflow);
var deserializedWorkflow = workflowSerializer.Deserialize(serialized);

var rehydratedWriteLine = ((deserializedWorkflow.Root as Flowchart).Activities.FirstOrDefault() as WriteLine);
```
...the `rehydratedWriteLine` expression value, `rehydratedWriteLine.Text.Expression.Value`, is no longer a variable...
```
ValueKind = Object : "{"id":"Workflow1:variable-1","name":"variableName","typeName":"String","value":"Some Value","storageDriverTypeName":"Elsa.Workflows.Services.WorkflowStorageDriver, Elsa.Workflows.Core"}"
    ValueKind: Object
```

Given this might occur with other types, I opted to use the `WelKnownTypes` pattern and a custom converter, so additional deserializations might be handled. The issue with the converter is an infinite recursion, which is why the factory's used and the converter's added in each invocation. Probably not performant, but hey, it got the job done:)

Our use case is dynamic workflow generation and submittal to the stand-alone engine over the wire, so preserving the integrity of the workflow through serialization is critical. This was causing a silent functional failure due to the absence of the variable despite successful workflow execution.

Hopefully that helps.

**Comment by sfmskywalker** [comment]
I see, thank you for the elaborate explanation! At first sight, I'm not sure I like the use of WellknownTypes here, but perhaps you're right and it is appropriate after all. I will give this some thought.

**Comment by sfmskywalker** [comment]
I (think I) was able to fix the issue with the following commit: 26b0e5535343d284d45c13ed5355b14d0cdd2f5b
I tested it against your ample code, and with this change, the deserialized Expression maintained the original Variable type.

I will merge that commit into the main branch from which preview packages will be built in case you want to try it.
Please let me know if you agree with the changes and whether it fixes the issue or not. 

Thanks!

**Comment by sfmskywalker** [comment]
Thank you, @tulrichtrimble, for your valuable contribution and effort on this issue. After reviewing your PR, I appreciate the approach and insights you've shared. However, I've recently pushed a simpler and more correct solution that addresses the problem directly in the main branch. While we won't be merging your PR this time, your willingness to contribute and help improve the project is highly appreciated. Please continue to share your ideas and contributions with us in the future!

**Comment by tulrichtrimble** [comment]
Hi Sipke,

I've kept up on this but neglected to thank you for addressing it. I'm glad
I could help and that you found a workable solution.

Cheers!
Tyler


Tyler Ulrich
Senior Architect


1515 Southeast Water Avenue, Portland, OR 97214
United States
www.trimble.com

**Comment by tulrichtrimble** [comment]
Hi Sipke,

Do you have a sense when This as well as Add workflow serialization and new
export endpoint
<https://github.com/elsa-workflows/elsa-core/commit/c601076437ab5a04bc3cad5e0845d8f0649b7b5c>
will
be released? We are deciding whether we need to run the repo as a
sub-module to get integration tests working.

Thank you for all the contributions,

Tyler




Tyler Ulrich
Senior Architect


1515 Southeast Water Avenue, Portland, OR 97214
United States
www.trimble.com

**Comment by sfmskywalker** [comment]
Hi Tyler,

The final 3.1 milestone release should occur in March, according to our stable release cadence plan.

But, you don't have to wait that long in order to consume the latest & greatest features & bugfixes. These, and all other commits to the `main` branch are built & published automatically to [the preview feed](https://f.feedz.io/elsa-workflows/elsa-3/nuget/index.json) as 3.1.0-preview.xxx versions.

For more information about how to consume the preview feed, please checkout the [Elsa NuGet Packages topic](https://v3.elsaworkflows.io/docs/installation/packages).

And of course, you always have the option to include elsa-core as a git sub module if you don't want to consume the preview feed.

**Pull request closed without merging**
