### PR TITLE
Fixes SQL quoted identifiers by `ISqlGenerationHelper` (#3430)

### LINKED ISSUE #3430: elsa.persistence.entityframework.mysql 2.9.2, mysql  error
#3384 This change causes MySQL errors. MySQL syntax does not support double quotes.   

I'm sorry for my poor English.

### PR DESCRIPTION
**Pull request by akunzai**
- Fixes #3430

### CODE REVIEW

**Review by sfmskywalker — APPROVED** [review]

**Comment by johnwc** [comment]
@sfmskywalker when can this patch be pushed to 2.10 preview? This killed our deployment, as we use MySql. Is there a way to get updates tested for each db library, so these things don't get accidently pushed to releases?

**Comment by sfmskywalker** [comment]
@johnwc It should be available as version 2.9.2-preview.558 from the MyGet feed. All pushes to the `master` and `2.9.x` branch are automatically build & deployed to the MyGet feed for people to try out fixes and features before they get released to NuGet. the 2.9.2-preview.558 is using the wrong minor version, it should have been 2.9.3-preview.558. I will fix that today, which will result in a new package version of 2.9.3-preview.{build} on MyGet.

**Comment by sfmskywalker** [comment]
Once [this build](https://ci.appveyor.com/project/sfmskywalker/elsa/builds/45479115) finishes successfully, 2.9.3-preview.563 will contain the fix from this PR.

**Comment by sfmskywalker** [comment]
I also merged 2.9.x into master just now, which means the [upcoming 2.10.564](https://ci.appveyor.com/project/sfmskywalker/elsa/builds/45479142) version on MyGet will contain the fix too, including other enhancements.

**Comment by johnwc** [comment]
@sfmskywalker The fixes I needed were in 2.10 preview, will that get built as well?

**Comment by johnwc** [comment]
@sfmskywalker The latest 2.10.564 has broken the web UI, only blank white pages now. With 404 on the `elsa-workflows-studio` assets.
image

**Comment by johnwc** [comment]
@sfmskywalker any traction on this? I'm trying to contribute the MySQL library for secrets, but can't work on it until this is resolved.

**Pull request merged**
