### PR TITLE
Replace custom distributed lock implementation with DistributedLock package

### PR DESCRIPTION
**Pull request by sfmskywalker**

### CODE REVIEW

**Comment by vip32** [comment]
Hi @sfmskywalker some feedback (i see that it is work in progress):
in preview7-1787 i suddenly see the following exception reagarding this new lockprovider.

note: this only happens when deployed in azure webapp (linux appservice). Localy on windows it works fine. also, before in preview7-1651 this also worked fine on azure webapp (linux appservice)

logs from app startup:
```
....
2021-04-07T19:03:20.475799831Z [19:03:20 INF] Running startup task ContinueRunningWorkflows
2021-04-07T19:03:20.489847504Z [19:03:20 DBG] Acquiring a lock on ContinueRunningWorkflows
2021-04-07T19:03:20.593526590Z Unhandled exception. System.TimeoutException: Timeout exceeded when trying to acquire the lock
2021-04-07T19:03:20.593573692Z    at Medallion.Threading.Internal.DistributedLockHelpers.ThrowTimeoutIfNull[T](ValueTask`1 task, String object) in C:\Users\mikea_000\Documents\Interests\CS\DistributedLock\DistributedLock.Core\Internal\DistributedLockHelpers.cs:line 142
2021-04-07T19:03:20.593587092Z    at Medallion.Threading.Internal.Helpers.Convert[TDerived,TBase](ValueTask`1 task, ValueTaskConversion _) in C:\Users\mikea_000\Documents\Interests\CS\DistributedLock\DistributedLock.Core\Internal\Helpers.cs:line 24
2021-04-07T19:03:20.593596993Z    at Elsa.Services.DistributedLockProvider.AcquireLockAsync(String name, Nullable`1 timeout, CancellationToken cancellationToken)
2021-04-07T19:03:20.593605493Z    at Elsa.StartupTasks.ContinueRunningWorkflows.ExecuteAsync(CancellationToken cancellationToken)
2021-04-07T19:03:20.593613993Z    at Elsa.Runtime.StartupRunner.StartupAsync(CancellationToken cancellationToken)
2021-04-07T19:03:20.593622194Z    at Elsa.HostedServices.StartupRunnerHostedService.StartAsync(CancellationToken cancellationToken)
2021-04-07T19:03:20.593630494Z    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2021-04-07T19:03:20.593638794Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2021-04-07T19:03:20.593646894Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2021-04-07T19:03:20.593655195Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
```

what kind of distributed lock is used? sqlserver?
just redeployed my old 1651 based webapp and it works fine again. maybe it's linux as the lock acquiring runs fine on windows.

**Comment by sfmskywalker** [comment]
Hi @vip32 , thanks for the feedback! 

The default lock provider uses [FileDistributedLock](https://github.com/madelson/DistributedLock/blob/master/DistributedLock.FileSystem/FileDistributedLock.cs), which gets initialized with `new DirectoryInfo(Path.GetTempPath()`.

The timeout for acquiring a lease on the `ContinueRunningWorkflows` is 10 seconds. Could it be that you have more than 1 instance running?

In any case, I will change the `AcquireLockAsync` method on Elsa's `DistributedLockProvider` to not throw an exception when a lock is not acquired in time, because when multiple instances are starting, only one of them needs a lock in order to prevent the others from continuing idle workflows (and not throw an exception).

**Comment by vip32** [comment]
what i see is that the exception is thrown immediatly, not in 10 seconds. As far as i know i  have one instance running (1 webapp, 1 scaled instance)

**Comment by vip32** [comment]
just tried the new preview7.1809 release and the lock error is now gone :)
issue can be closed, thx!

**Comment by sfmskywalker** [comment]
Great, thanks for confirming!

**Pull request merged**
