### PR TITLE
Enhancement mail kit send mail

### PR DESCRIPTION
**Pull request by Andale-online**
Please have a look...

What are the options i had to comment out?

### CODE REVIEW

**Comment by Andale-online** [comment]
Don't merge this... I'll make a new branch later... Only the last commit is meant

**Comment by sfmskywalker** [comment]
I think something went wrong when you created this PR. It contains way too many changes, most of which unrelated to the Mailkit implementation. Perhaps some merge thing? Let me know if you need help.

**Comment by sfmskywalker** [comment]
I spoke too soon and didn't see your last comment :)

**Comment by sfmskywalker** [comment]
It looks fine to me. I'll test it once you have a clean branch off of `develop` with just your Mailkit changes. Regarding the options you commented out, I think it's fine. `SmtpClient` supports directory pickup. Not sure if Mailkit supports it too. If not, then just remove these options. If so, we'll refactor.

**Comment by sfmskywalker** [comment]
Hi @Andale-online , I have some spare time today to try and finish the 1.1 milestone. I took the liberty to take your code and tweak it a little bit: https://github.com/elsa-workflows/elsa-core/pull/194

I'll close this PR, but will make sure to credit you with proper attribution. Thanks!

**Pull request closed without merging**
