### PR TITLE
Fix appveyor build issue

### PR DESCRIPTION
**Pull request by jwillmer**

### CODE REVIEW

**Review by sfmskywalker — APPROVED** [review]

**Comment by craigfowler** [comment]
@jwillmer Hmm, I'm not sure this has fixed it 100%.  It gets further than it did before but then it dies with a different error message, still seemingly related to the container 😕

**Comment by jwillmer** [comment]
O.K. but with this I don't know what to do 😕  `failed to shutdown container`

**Comment by jwillmer** [comment]
Is there a reason why we build the docker container in appveyor? Maybe it is pointless to fix?

**Comment by sfmskywalker** [comment]
No other reason than simple convenience. That being said, I've been considering to separate the docker builds from the package builds. Ultimately the sample projects will be moved to their own repo anyway.

**Comment by jwillmer** [comment]
Now it worked, did someone fix it? https://ci.appveyor.com/project/sfmskywalker/elsa

**Pull request merged**
