### PR TITLE
Fixed issue where named activities couldn't be used with Then()

### PR DESCRIPTION
**Pull request by jamesdoran**
To reproduce, run Sample12 after pulling in previous PR. You'll get a "sequence contains no elements" error.

### CODE REVIEW

**Comment by sfmskywalker** [comment]
Thanks!

**Comment by sfmskywalker** [comment]
I just noticed this and the other PR got merged into master instead of develop. Not a big deal, but I’m writing it down so I don’t forget to merge it into develop tomorrow 💁‍♂️

**Comment by jamesdoran** [comment]
Apologies Sipke, I'll target develop next time

**Comment by sfmskywalker** [comment]
No worries!

**Pull request merged**
