### PR TITLE
3038: retention module: delete execution logs

### PR DESCRIPTION
**Pull request by mlditga**
Hello,
This may fix the issue #3038. Let me know if I need to change something.

### CODE REVIEW

**Comment by mlditga** [comment]
Hello, 
we may consider updating MongoDB provider but unfortunately we won't be able to do it for YesSQL as we don't know it at all. If we modify mongo provider should we put the deletion in a transaction?
Thank you!

**Comment by sfmskywalker** [comment]
Hi @mlditga 

Just updating the MongoDB provider is enough, you don't have to do it also for YesSQL.
Doing it in a transaction would be nice, but not a hard requirement.

Thank you!

**Comment by jdevillard** [comment]
Hello, 

@mlditga , have you update the mongoDb provider? 

I think this PR should be close without merge and a new PR with only the MongoDb provider should be done.
In the same way, I'm on my side proposing perf enhancement on the retention module.

**Comment by mlditga** [comment]
Hello,
Sorry, no. We ended up implementing a custom code for db cleaning as we had a custom collection anyway :/ But this PR can probably be closed.

**Comment by sfmskywalker** [comment]
Thanks for letting us know @mlditga. We'll close this PR.

**Pull request closed without merging**
