### PR TITLE
Create tes.yml

### PR DESCRIPTION
**Pull request by MarkHarris21**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=837) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=837) before we can accept your contribution.<br/><br/>:x: MarkHarris21 [sign now](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=837)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/elsa-workflows/elsa-core?pullRequest=837) it.</sub>

**Comment by effigies** [comment]
@jwillmer Cryptocurrency miner. Please cancel actions, report user and block.

**Comment by jwillmer** [comment]
Thx for the notification @effigies . User is reported. I will check if we can modify the actions to prevent this in the future.

**Comment by effigies** [comment]
Please let me know if you find something. I spent some time looking into it and couldn't find anything that would stop this attack.

**Comment by jwillmer** [comment]
I found [this report](https://dev.to/thibaultduponchelle/the-github-action-mining-attack-through-pull-request-2lmc) that shows the current options you can use to limit GitHub Actions. But I need to look into them, especially the "selected actions" option. Maybe we can use it to only allow "whitelisted" actions.
image

**Comment by effigies** [comment]
I read that as saying you can limit "<provider>/<action>@<version>" actions, but this just uses GHA's built-in bash.

**Comment by jwillmer** [comment]
@effigies I have asked @sfmskywalker to modify the action policies to only allow actions from verified publishers with one exception. You can find this tab at `https://github.com/organizations/[ORGANIZATION]/settings/actions`

image

**Pull request closed without merging**
