### PR TITLE
Fix error unsubscribe mqtt client 

### PR DESCRIPTION
**Pull request by mircotamburini**
Sorry i commited also opcua activities

### CODE REVIEW

**Comment by sfmskywalker** [comment]
I'd happily accept your Mqqt fixes, but I'm not yet familiar with opcua. Therefore, let's leave them out for now. Maybe later.

**Comment by mircotamburini** [comment]
> I'd happily accept your Mqqt fixes, but I'm not yet familiar with opcua. Therefore, let's leave them out for now. Maybe later.

sorry i made a mistake

**Comment by mohdali** [comment]
> > I'd happily accept your Mqqt fixes, but I'm not yet familiar with opcua. Therefore, let's leave them out for now. Maybe later.
> 
> sorry i made a mistake

@mircotamburini Do you intend to contribute the OPC UA activities as well? I would be interested in that if you make a separate PR if @sfmskywalker doesn't mind.

**Comment by mircotamburini** [comment]
> hope you don't mind.

Absolutely not, as i told i made a mistake in pull-request... im sorry for that but i was really busy on a IoT (internet of the thing) project using Elsa... but i try to do that during this days.  I also interested to add also new protocol important in Industry 4.0 automation like MTConnect , Modbus, Siemens S7

**Pull request closed without merging**
