### PR TITLE
Add .NET 9.0 target

### LINKED ISSUE #6115: [BUG] Elsa is not compatible with EFC9
## Description
EFC made a binary breaking change in v9 which was in https://github.com/dotnet/efcore/pull/34257
```
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Int32> Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteDeleteAsync(System.Linq.IQueryable`1<!!0>, System.Threading.CancellationToken)'.
   at async Task<long> Elsa.EntityFrameworkCore.Common.Store<TDbContext, TEntity>.DeleteWhereAsync(Func<IQueryable<TEntity>, IQueryable<TEntity>> query, CancellationToken cancellationToken)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<long> Elsa.EntityFrameworkCore.Common.Store<TDbContext, TEntity>.DeleteWhereAsync(Func<IQueryable<TEntity>, IQueryable<TEntity>> query, CancellationToken cancellationToken)
   at async ValueTask<long> Elsa.EntityFrameworkCore.Modules.Runtime.EFCoreWorkflowInboxMessageStore.DeleteManyAsync(WorkflowInboxMessageFilter filter, PageArgs pageArgs, CancellationToken cancellationToken)
   at async Task Elsa.Workflows.Runtime.HostedServices.WorkflowInboxCleanupHostedService.CleanupExpiredMessages(CancellationToken cancellationToken)
   at async Task Elsa.Workflows.Runtime.HostedServices.WorkflowInboxCleanupHostedService.ExecuteAsync(CancellationToken stoppingToken)
```
so elsa must add a 9.0 target.

### PR DESCRIPTION
**Pull request by Suchiman**
Pomelo.MySQL has not yet released an EFC9 provider and looks abandoned so MySQL is excluded.

fixes #6115

- - -
This change is [Reviewable](https://reviewable.io/reviews/elsa-workflows/elsa-core/6186)

### CODE REVIEW

**Review by sfmskywalker — APPROVED** [review]
Looks great @Suchiman !

**Comment by Suchiman** [comment]
Rebased to resolve conflicts. Also added .net9 setup to the packages.yml too.

**Comment by AlexSynakh** [comment]
@Suchiman It seems that Oracle has released EFC9 provider, is it possible to also include it in this PR?

**Comment by Suchiman** [comment]
rebased and added support for oracle's EFC9 provider

**Comment by bachampson** [comment]
Any chance of this being merged and released since its approved?

**Pull request merged**
