### PR TITLE
Elsa 2 .NET 8 Support

### LINKED ISSUE #4667: .Net 8 support
Any idea when we will have .net 8 support so we can update our projects?
Thank you.

### PR DESCRIPTION
**Pull request by swimmesberger**
Fixes #4667 

Used #3476 as a guideline

Note: MySQL Provider is still in beta release.

### CODE REVIEW

**Comment by swimmesberger** [comment]
@dotnet-policy-service agree

**Review by sfmskywalker — APPROVED** [review]
Thank you! 😃

**Comment by sorensenmatias** [comment]
@swimmesberger Great that you did this PR, it will help us a lot. Any news on proceeding with it?

**Comment by swimmesberger** [comment]
> @swimmesberger Great that you did this PR, it will help us a lot. Any news on proceeding with it?

The changes are merged into 2.x I guess you simply have to publish a new nuget package of 2.x to get it out.

**Pull request merged**
